name: Run Tests and Upload Report

on:
  schedule:
    - cron: '30 1 * * *' # 7:00am IST = 1:30am UTC
  workflow_dispatch:

jobs:
  test-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven tests
        run: mvn test -DBASE_URI=${{ secrets.BASE_URI }} -DACCOUNTS_BASE_URI=${{ secrets.ACCOUNTS_BASE_URI }}

      - name: Upload test result XML
        run: |
          for file in target/surefire-reports/TEST-*.xml; do
            curl -X POST "https://qa-dashboard-api.onrender.com/upload-report" \
              -H "X-API-KEY: qad_e8be0996c7ad44c4a2164373c582453b" \
              -F "files=@$file"
          done

